### ISSUE TITLE
长期维护吗 

### ISSUE THREAD

**Issue by bestv5** [KspTooi/IDEATheme-Eclipse#1]
长期维护吗

**Comment by KspTooi** [comment]
是的 长期维护
________________________________
发件人: xuran.li ***@***.***>
发送时间: 2021年3月30日 0:42
收件人: KspTooi/IDEATheme-Eclipse ***@***.***>
抄送: Subscribed ***@***.***>
主题: [KspTooi/IDEATheme-Eclipse] 长期维护吗 (#1)


长期维护吗

―
